# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.

name: Python Dependency Vulnerability Audit

on:
  push:
    branches:
      - "master"
      - "[0-9].[0-9]*"
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
  schedule:
    - cron: "0 6 * * 1"

# cancel previous workflow jobs for PRs
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  pip-audit:
    runs-on: ubuntu-24.04
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Check for file changes
        id: check
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/change-detector/
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        if: github.event_name != 'pull_request' || steps.check.outputs.python
        uses: ./.github/actions/setup-backend/
        with:
          requirements-type: base

      - name: Install pip-audit
        if: github.event_name != 'pull_request' || steps.check.outputs.python
        run: uv pip install --system pip-audit

      - name: Run pip-audit
        if: github.event_name != 'pull_request' || steps.check.outputs.python
        run: pip-audit -r requirements/base.txt --desc --output pip-audit-results.txt || true

      - name: Display audit results
        if: github.event_name != 'pull_request' || steps.check.outputs.python
        run: cat pip-audit-results.txt

      - name: Check for vulnerabilities
        if: github.event_name != 'pull_request' || steps.check.outputs.python
        run: pip-audit -r requirements/base.txt --strict
